export const VENDOR_CATEGORIES = [
  { slug: "salle-des-fetes", name_fr: "Salles des fêtes", name_ar: "قاعات الحفلات", icon: "Building2", count: 0 },
  { slug: "traiteur", name_fr: "Traiteurs", name_ar: "مطاعم ومأكولات", icon: "UtensilsCrossed", count: 0 },
  { slug: "photographe", name_fr: "Photographes", name_ar: "مصورون", icon: "Camera", count: 0 },
  { slug: "videaste", name_fr: "Vidéastes", name_ar: "مصورو فيديو", icon: "Video", count: 0 },
  { slug: "orchestre-dj", name_fr: "Orchestres & DJ", name_ar: "أوركسترا ودي جي", icon: "Music", count: 0 },
  { slug: "decoration", name_fr: "Décoration & Fleuristes", name_ar: "ديكور وورود", icon: "Flower2", count: 0 },
  { slug: "couturier", name_fr: "Couturiers & Tenues", name_ar: "خياطون وأزياء", icon: "Shirt", count: 0 },
  { slug: "henne", name_fr: "Artistes Henné", name_ar: "فنانون حناء", icon: "Paintbrush", count: 0 },
  { slug: "patisserie", name_fr: "Pâtisseries & Cake", name_ar: "حلويات وكيك", icon: "CakeSlice", count: 0 },
  { slug: "voiture-luxe", name_fr: "Voitures de luxe", name_ar: "سيارات فاخرة", icon: "Car", count: 0 },
  { slug: "bijouterie", name_fr: "Bijouterie & Accessoires", name_ar: "مجوهرات", icon: "Gem", count: 0 },
  { slug: "faire-part", name_fr: "Faire-part & Papeterie", name_ar: "بطاقات ودعوات", icon: "Mail", count: 0 },
  { slug: "wedding-planner", name_fr: "Wedding Planners", name_ar: "منظمي حفلات", icon: "CalendarCheck", count: 0 },
] as const;

export const WILAYAS = [
  { code: 16, name_fr: "Alger", name_ar: "الجزائر" },
  { code: 31, name_fr: "Oran", name_ar: "وهران" },
  { code: 25, name_fr: "Constantine", name_ar: "قسنطينة" },
  { code: 13, name_fr: "Tlemcen", name_ar: "تلمسان" },
  { code: 6, name_fr: "Béjaïa", name_ar: "بجاية" },
  { code: 23, name_fr: "Annaba", name_ar: "عنابة" },
  { code: 19, name_fr: "Sétif", name_ar: "سطيف" },
  { code: 15, name_fr: "Tizi Ouzou", name_ar: "تيزي وزو" },
  { code: 9, name_fr: "Blida", name_ar: "البليدة" },
  { code: 27, name_fr: "Mostaganem", name_ar: "مستغانم" },
  { code: 35, name_fr: "Boumerdès", name_ar: "بومرداس" },
  { code: 47, name_fr: "Ghardaïa", name_ar: "غرداية" },
] as const;

export const CHECKLIST_CATEGORIES = [
  { slug: "khotba", name_fr: "Khotba — Demande en mariage", name_ar: "الخطبة", icon: "Heart" },
  { slug: "fatiha", name_fr: "Fatiha — Fiançailles", name_ar: "الفاتحة", icon: "BookOpen" },
  { slug: "kitab", name_fr: "Kitab — Acte de mariage", name_ar: "الكتاب", icon: "FileText" },
  { slug: "chouar", name_fr: "Chouar — Trousseau", name_ar: "الشوار", icon: "Luggage" },
  { slug: "henne", name_fr: "Hannouna — Nuit du Henné", name_ar: "الحنة", icon: "Palette" },
  { slug: "jour-j", name_fr: "Jour J — La fête", name_ar: "يوم الزفاف", icon: "PartyPopper" },
  { slug: "sebiaa", name_fr: "Sebiaa — Le lendemain", name_ar: "السبوع", icon: "Sun" },
] as const;

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Amira & Karim",
    location: "Alger",
    date: "Mai 2026",
    rating: 5,
    text: "LELLA nous a trouvé la salle des fêtes parfaite en moins de 48h. Le traiteur était délicieux et le photographe a capturé chaque moment magique. Notre mariage a été au-delà de nos rêves.",
    highlight: "La salle parfaite en 48h",
    avatar: "AK",
  },
  {
    id: 2,
    name: "Nadia & Sofiane",
    location: "Oran",
    date: "Mars 2026",
    rating: 5,
    text: "Grâce à LELLA, nous avons trouvé une wedding planner exceptionnelle qui a coordonné toute la cérémonie du Henné. L'artiste henné était incroyable — toutes mes invitées étaient émerveillées.",
    highlight: "Un Henné de rêve",
    avatar: "NS",
  },
  {
    id: 3,
    name: "Inès & Mohamed",
    location: "Constantine",
    date: "Avril 2026",
    rating: 5,
    text: "De la Khotba au Sebiaa, LELLA nous a accompagnés à chaque étape. La checklist intégrée nous a évité tellement de stress. Je recommande à 100% à tous les futurs mariés.",
    highlight: "Accompagnement complet",
    avatar: "IM",
  },
  {
    id: 4,
    name: "Lina & Rayan",
    location: "Tlemcen",
    date: "Juin 2026",
    rating: 4,
    text: "Nous avons trouvé notre orchestré et notre couturière via LELLA. La qualité des prestataires est exceptionnelle. Seul petit bémol : nous aurions aimé plus de choix dans notre wilaya.",
    highlight: "Des prestataires de qualité",
    avatar: "LR",
  },
  {
    id: 5,
    name: "Sarah & Yacine",
    location: "Béjaïa",
    date: "Février 2026",
    rating: 5,
    text: "LELLA a rendu l'organisation de notre mariage tellement plus simple. La comparaison des prestataires, les avis vérifiés, le budget tracker — tout est pensé pour nous faciliter la vie.",
    highlight: "Une organisation simplifiée",
    avatar: "SY",
  },
] as const;

export const FEATURED_VENDORS = [
  {
    id: 1,
    name: "Palais d'El-Mouradia",
    category: "Salles des fêtes",
    categorySlug: "salle-des-fetes",
    location: "Alger",
    rating: 4.9,
    reviews: 127,
    image: null,
    badge: "Top choix 2026",
    description: "Salle de réception luxueuse avec vue panoramique, capacité 500 personnes, jardin andalou.",
  },
  {
    id: 2,
    name: "Traiteur Les Délices d'Orient",
    category: "Traiteurs",
    categorySlug: "traiteur",
    location: "Oran",
    rating: 4.8,
    reviews: 93,
    image: null,
    badge: "Coup de cœur",
    description: "Cuisine algérienne traditionnelle revisée, spécialités oranaises, pâtisserie fine.",
  },
  {
    id: 3,
    name: "Studio Lumières d'Afrique",
    category: "Photographes",
    categorySlug: "photographe",
    location: "Alger",
    rating: 5.0,
    reviews: 64,
    image: null,
    badge: "Expert",
    description: "Photographie de mariage artistique, reportage émotion, album luxe fait main.",
  },
  {
    id: 4,
    name: "Orchestre Ziryab",
    category: "Orchestres & DJ",
    categorySlug: "orchestre-dj",
    location: "Constantine",
    rating: 4.9,
    reviews: 88,
    image: null,
    badge: "Tendance",
    description: "Orchestre fusion chaâbi-andalou-moderne, 15 musiciens, sonorisation haut de gamme.",
  },
  {
    id: 5,
    name: "Yasmina Henné Art",
    category: "Artistes Henné",
    categorySlug: "henne",
    location: "Alger",
    rating: 4.9,
    reviews: 156,
    image: null,
    badge: "Meilleur note",
    description: "Artiste henné renommée, motifs traditionnels et modernes, cérémonie clé en main.",
  },
  {
    id: 6,
    name: "Chedda Couture",
    category: "Couturiers & Tenues",
    categorySlug: "couturier",
    location: "Tlemcen",
    rating: 4.8,
    reviews: 72,
    image: null,
    badge: "Artisan d'exception",
    description: "Chedda tlemcenienne traditionnelle, karakou moderne, robes de cérémonie sur mesure.",
  },
] as const;

export const SITE_CONFIG = {
  name: "LELLA",
  tagline: "La plateforme des événements familiaux en Algérie",
  email: "contact@lella.dz",
  social: {
    instagram: "https://instagram.com/lella.dz",
    facebook: "https://facebook.com/lella.dz",
    tiktok: "https://tiktok.com/@lella.dz",
  },
} as const;
